apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice3-admin-formules
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice3-admin-formules
  template:
    metadata:
      labels:
        app: microservice3-admin-formules
    spec:
      containers:
        - name: microservice3-admin-formules
          image: aminabakkali/microservice3-admin-formules
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: microservice3-admin-formules
spec:
  type: LoadBalancer
  selector:
    app: microservice3-admin-formules
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084