apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice3-admin-formules
  labels:
    app: microservice3-admin-formules
spec:
  replicas: 1
  selector:
    matchLabels:
      app : microservice3-admin-formules
  template:
    metadata:
      labels:
        app: microservice3-admin-formules
    spec:
      containers:
        - name: microservice3-admin-formules
          image: aminabakkali/microservice3-admin-formules
          imagePullPolicy: Always
          ports:
            - containerPort: 8084

---

kind: Service
apiVersion: v1
metadata:
  name:  user-service-svc
spec:
  selector:
    app:  microservice3-admin-formules
  ports:
    - port:  8080
      targetPort:  8084